### ISSUE TITLE
Add Save to current note directory option in Attachment override

### ISSUE THREAD

**Issue by Archie-2021** [jglev/obsidian-paste-mode#24]
Add an option in 'Attachment override' so that we can set the attachment location for certain folders to 'Same as current note directory' like how it is for core obsidian. As an example, I like to have attachments for my projects (which all are located in a certain folder) to be next to them and be all in one folder, but I want the rest of my vault to have their attachments in a central location. With the current settings I can't have that.

Thank you for this supper useful plugin. It was really needed.

**Comment by jglev** [comment]
> Thank you for this supper useful plugin. It was really needed.

Thank you for your kind words!

> Add an option in 'Attachment override' so that we can set the attachment location for certain folders to 'Same as current note directory' like how it is for core obsidian.

I take your point about how this could be useful. I've added the ability to use "`{current}`" in all override attachment locations as well as the default location in [`v5.0.1-beta1`](https://github.com/jglev/obsidian-paste-mode/releases/tag/5.0.1-beta1) just now. Would you feel comfortable trying out that beta version and checking that it works on your system, as well? (If not, no worries, of course! I haven't yet added automated testing to this codebase, and so welcome as many testers as possible and thought to ask.)

**Comment by Archie-2021** [comment]
> > Thank you for this supper useful plugin. It was really needed.
> 
> Thank you for your kind words!
> 
> > Add an option in 'Attachment override' so that we can set the attachment location for certain folders to 'Same as current note directory' like how it is for core obsidian.
> 
> I take your point about how this could be useful. I've added the ability to use "`{current}`" in all override attachment locations as well as the default location in [`v5.0.1-beta1`](https://github.com/jglev/obsidian-paste-mode/releases/tag/5.0.1-beta1) just now. Would you feel comfortable trying out that beta version and checking that it works on your system, as well? (If not, no worries, of course! I haven't yet added automated testing to this codebase, and so welcome as many testers as possible and thought to ask.)

Thank you, 
I tested it on a new vault and it is working like a charm, Hoping to see it soon on the main branch.

**Comment by jglev** [comment]
Great, thank you! I've released [v5.0.1](https://github.com/jglev/obsidian-paste-mode/releases/tag/5.0.1) just now!

**Comment by Archie-2021** [comment]
> Great, thank you! I've released [v5.0.1](https://github.com/jglev/obsidian-paste-mode/releases/tag/5.0.1) just now!

Thanks
