### ISSUE TITLE
Paste image mode?

### ISSUE THREAD

**Issue by tiktuk** [jglev/obsidian-paste-mode#26]
Hi,

Just found your plugin when looking for a solution to this issue: [Image copied in Safari is pasted as url - Bug reports - Obsidian Forum](https://forum.obsidian.md/t/image-copied-in-safari-is-pasted-as-url/53506).

Apparently Safari lists the url above the image data in the clipboard, which causes that to be pasted instead of the image.

Would it be possible to make a new mode where image data always takes precedence?

**Comment by jglev** [comment]
Thank you for reaching out!

I'm sorry to hear that this is affecting at least some Safari use-cases. I agree with the posters on the linked thread that this sounds like an issue that would ideally be solved upstream in Safari. Unfortunately, in any case, I don't have ready access to Safari myself to test any potential fixes. I would be open to a Pull Request around this, even if I would also be wary of proposed changes, that this edge case not accidentally affect existing functionality that works across other browsers.

Would this be a place where something like the

**Comment by jglev** [comment]
(Sorry for closing this just now with a half-written post -- GitHub seems to have a "Close and Post" keyboard shortcut that I didn't expect!)

Thank you for reaching out!

I'm sorry to hear that this is affecting at least some Safari use-cases. I agree with the posters on the linked thread that this sounds like an issue that would ideally be solved upstream in Safari. Unfortunately, in any case, I don't have ready access to Safari myself to test any potential fixes. I would be open to a Pull Request around this, although I would also be wary of proposed changes, in order that this edge case not accidentally affect existing functionality that works across other browsers.

Would this be a place where something like the [Apply Patterns plugin](https://github.com/jglev/obsidian-apply-patterns-plugin) could help to strip incoming text from the clipboard, leaving just a link to the image? Or where this plugin's `src attribute copy regex` setting could be used to definitely download the copied file?

I'm going to keep this Issue marked Closed, to reflect that I'm not currently planning to develop around it. But please do feel free to correspond here more!
